# Based off of these rules: https://github.com/sasstools/sass-lint/tree/master/docs/rules
#
# KEY #
# 0 = ignore
# 1 = warn
# 2 = throw error
#
# Example(s):
#
# rule-one: 0
#
# Rules with options:
#
# rule-two:
#  - 0
#  -
#   option-one: 4
#   option-two: true

options:
    formatter: stylish
files:
    include: '**/*.s+(a|c)ss'
rules:
    # Extends
    extends-before-mixins: 0
    extends-before-declarations: 0
    placeholder-in-extend: 0

    # Mixins
    mixins-before-declarations: 0

    # Line Spacing
    one-declaration-per-line: 2
    empty-line-between-blocks: 2
    single-line-per-selector: 2

    # Disallows
    no-color-keywords: 0
    no-color-literals: 0
    no-css-comments: 0
    no-debug: 1
    no-duplicate-properties: 0
    no-empty-rulesets: 0
    no-extends: 0
    no-ids: 0
    no-important: 0
    no-invalid-hex: 2
    no-mergeable-selectors: 2
    no-misspelled-properties: 0
    no-qualifying-elements: 0
    no-trailing-zero: 2
    no-transition-all: 0
    no-url-protocols: 0
    no-vendor-prefixes: 0
    no-warn: 1
    no-trailing-whitespace: 2

    # Nesting
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0

    # Name Formats
    class-name-format: 0
    function-name-format: 0
    mixin-name-format: 0
    placeholder-name-format: 0
    variable-name-format:
        - 0
        - allow-leading-underscore: false

    # Style Guide
    border-zero: 0
    brace-style:
        - 2
        - style: '1tbs'
          allow-single-line: false
    clean-import-paths: 0
    empty-args: 0
    hex-length:
        - 2
        - style: short
    hex-notation:
        - 2
        - style: lowercase
    indentation:
        - 2
        - size: 4
    leading-zero: 0
    nesting-depth:
        - 1
        - max-depth: 4
    property-sort-order: 0
    quotes:
        - 2
        - style: single
    shorthand-values:
        - 2
        - allowed-shorthands:
              - 1
              - 2
    url-quotes: 0
    variable-for-property: 0
    zero-unit: 2

    # Inner Spacing
    space-after-comma: 2
    space-before-colon: 2
    space-after-colon: 2
    space-around-operator: 2
    space-before-brace: 2
    space-before-bang: 2
    space-after-bang: 0
    space-between-parens: 2

    # Final Items
    trailing-semicolon: 2
    final-newline: 2
